### ISSUE TITLE
Support metrics 3.0

### ISSUE THREAD

**Issue by tomfitzhenry** [BrightcoveOS/metrics-graphite-pickle#7]
http://metrics.codahale.com/about/release-notes/

metrics 3.0 uses a different package (com.codahale rather than com.yammer), meaning metrics-graphite-pickle compatibility is broken. I think the reporter API has changed too.

**Comment by abeerends** [comment]
Are there any plans to do this?  Or a willingness to accept a pull request?

**Comment by samperman** [comment]
I'd like to do it, but just haven't gotten to it yet... I would be willing to accept a pull request.

However, I don't think the right thing to do is to keep this as a separate project anymore. I originally created this as a separate project because I was using jython for the pickling. Coda was reluctant (rightly so) to add a jython dependency to the `metrics-graphite` project.  However, we no longer depend on jython.  I think the _right_ thing to do would be to add these classes into a pull request directly on `metrics-graphite` so everyone gets the pickle support automatically without a separate dependency.

**Comment by samperman** [comment]
I created a pull request for this. Keep an eye on it, if you want metrics 3 support.

https://github.com/dropwizard/metrics/pull/536
